import ollama

# MOCK FOR A WHILE, UNTIL WE HAVE A REAL FINE-TUNED MODEL

class FinetunedKoyashLLM:
    def __init__(self, 
                 system_prompt : str = "Ты - Koyash Ассистент", 
                 temperature : float = 0.7):
        self.system_prompt = system_prompt
        self.temperature = temperature
        self.name = "FinetunedKoyashLLM: qwen2.5:32b"

    def get_response(self, user_prompt: str, temperature: float = None) -> ollama.ChatResponse:
        """
        Get a response from the model based on the system and user prompts.

        Args:
            system_prompt (str): The system prompt to set the context for the model.
            user_prompt (str): The user prompt containing the question or request.

        Returns:
            str: The response generated by the model.
        """

        response = ollama.chat(
            model="qwen2.5:32b",
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            options={"temperature": temperature if temperature is not None else self.temperature},
        )

        return response

    def get_answer(self, response : ollama.ChatResponse) -> str:
        return response['message']['content']
